version: '2'

networks:
  basic:

services:

  fabric-ca:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: fabric-ca-server
    ports:
        - "7054:7054"
    environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client
    volumes:
        - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
        - "./fabric-ca-client:/etc/hyperledger/fabric-ca-client"
    command: sh -c 'fabric-ca-server init -b admin:adminpw && fabric-ca-server start -b admin:adminpw'
    networks:
      - basic
